import 'modellek.dart';

class HalfajAdatok {
  static String _ph(String nev) => 'https://placehold.co/600x400/161616/69F0AE?text=${Uri.encodeComponent(nev)}';

  static List<Halfaj> getMagyarHalFauna() {
    return [
      Halfaj(
        id: 'hal_01', nev: 'Ponty', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '30 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '05.02 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Testalkata rendkívül változatos (tőponty, nyurgaponty, tükörponty), háta sötétzöldes, oldala aranysárga. Vizeink legnépszerűbb horgászhalaként az iszapos, táplálékban gazdag mederfenéket kedveli, ahol 4 bajuszszálával kutat férgek, kagylók és rovarlárvák után. Nyáron a melegedő, oxigéndús sekélyesekben, télen a mélyebb vermekben tartózkodik. Horgászata rendkívül sokrétű: a klasszikus fenekezéstől a modern feeder és bojlis technikákig bármivel fogható. Legjobb csalijai az erjesztett kukorica, tigrismogyorós vagy gyümölcsös bojlik, ízesített pelletek és az élő csontkukac. Fárasztása során kitartó, erőteljes kirohanásokkal védekezik.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Cyprinus_carpio_02.jpg/800px-Cyprinus_carpio_02.jpg', _ph('Ponty 2'), _ph('Ponty 3')],
      ),
      Halfaj(
        id: 'hal_02', nev: 'Compó', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '25 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '05.02 - 06.15.', szabalyozasEve: '2024',
        megjegyzes: 'A "halak orvosának" is hívott compó gyönyörű, zöldes-aranyfényű, apró pikkelyes, rendkívül nyálkás bőrű hal. Hivatalosan a hímek hasúszója jóval nagyobb és kanalazottabb, mint a nőstényeké. Kifejezetten a dús vízinövényzettel (hínáros, tavirózsás) benőtt, iszapos fenekű tavakat és csendes holtágakat kedveli. Tápláléka zömmel apró csigákból, férgekből és szúnyoglárvákból áll. Óvatos kapása miatt finomszerelékes úszózással, gilisztával, csontival, vagy apró csemegekukoricával érdemes célba venni az iszapos aljzaton.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Tinca_tinca_Prague.jpg/800px-Tinca_tinca_Prague.jpg', _ph('Compó 2'), _ph('Compó 3')],
      ),
      Halfaj(
        id: 'hal_03', nev: 'Márna', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '40 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Rendkívül izmos, áramlatkedvelő folyóvízi harcos, hengeres testtel, alsó állású húsos szájjal és 4 jellegzetes bajuszszállal. Főként a sebes sodrású, sóderes vagy kavicsos aljzatú szakaszokon él, ahol erős uszonyaival tapad a fenékhez. Vegyes táplálkozású: a rovarlárvák és csigák mellett a kishalakat is elkapja. Feeder botos fenekezéssel, sajttal, kolbászos pelletekkel, piócával vagy nagy csonti/giliszta csokorral fogható a leghatékonyabban. Fontos: ikrája és hasüregének fekete hártyája emberre enyhén mérgező, fogyasztás előtt alaposan el kell távolítani!',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Barbus_barbus.jpg/800px-Barbus_barbus.jpg', _ph('Márna 2'), _ph('Márna 3')],
      ),
      Halfaj(
        id: 'hal_04', nev: 'Paduc', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '20 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Nyúlánk, ezüstösen csillogó folyóvízi hal, melynek legfőbb ismertetőjegye az alsó állású, egyenes vágású, porcos "véső" ajak. Ezzel a különleges szájjal kaparja le a kövekre tapadt algabevonatot és apró szervezeteket az erős sodrásban. Hatalmas csapatokban jár, gyakran látni, ahogy a fenéken táplálkozva meg-megvillantja ezüstös oldalát (paducvillogás). Legeredményesebben folyóvízi úszózással (rakós vagy bolognai bottal), sajtos-földes etetőanyaggal, kenyérrózsával vagy csontkukaccal fogható.',
        kepek: [_ph('Paduc 1'), _ph('Paduc 2'), _ph('Paduc 3')],
      ),
      Halfaj(
        id: 'hal_05', nev: 'Dévérkeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Vizeink leggyakoribb, kifejezetten magas hátú, oldalról erősen lapított keszegféléje. Az idősebb ("lapát") példányok színe a sötét bronzostól a szürkés-feketéig terjedhet. Alsó állású, harmonikaszerűen kinyújtható csőszerű szájával valósággal kiporszívózza a mederfenék iszapjából a szúnyoglárvákat és férgeket. Csapatosan él mind folyóinkban, mind állóvizeinkben. Édes-fűszeres (fahéjas, karamelles, mogyorós) etetőanyagokkal, gilisztával, pinkivel vagy szúnyoglárvával bőséges zsákmányt adhat fenekezve vagy úszózva.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Abramis_brama_Prague_Vltava_1.jpg/800px-Abramis_brama_Prague_Vltava_1.jpg', _ph('Dévérkeszeg 2'), _ph('Dévérkeszeg 3')],
      ),
      Halfaj(
        id: 'hal_06', nev: 'Bodorka', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Kisebb termetű, ezüstös-zöldes pikkelyű hal, melynek legbiztosabb ismertetőjegye a narancssárga vagy élénkpiros írisz (szem). Minden hazai vizünkben megtalálható, rendkívül alkalmazkodóképes faj. Táplálékát vízinövények törmeléke, algák és apró rákfélék alkotják. Egész évben, még a jég alól is aktívan táplálkozik. Könnyű finomszerelékes úszózással, sötét tónusú, pörkölt magvas etetőanyaggal, 1-2 szem pinkivel, csontival vagy kendermaggal kiválóan fogható vízközt és fenék közelében is.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Rutilus_rutilus_Prague_Vltava_2.jpg/800px-Rutilus_rutilus_Prague_Vltava_2.jpg', _ph('Bodorka 2'), _ph('Bodorka 3')],
      ),
      Halfaj(
        id: 'hal_07', nev: 'Vörösszárnyú keszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Küllemében a bodorkához hasonlít, de szája egyértelműen felső állású (felfelé nyílik), uszonyai pedig – ahogy a neve is mutatja – élénk, lángoló vérvörösek. Kifejezetten a vízfelszín közelében tartózkodik, ahol a vízre hulló rovarokra, bogarakra vadászik, és a sekély, növényzettel (nádasokkal, hínárosokkal) sűrűn benőtt részeket kedveli. Vízfelszíni vagy vízközti könnyű úszós felszereléssel, kenyérgyurmával, csontival, sőt, nyári estéken apró száraz műléggyel is rendkívül szórakoztató a horgászata.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Scardinius_erythrophthalmus_Prague_Vltava_1.jpg/800px-Scardinius_erythrophthalmus_Prague_Vltava_1.jpg', _ph('Vörösszárnyú 2'), _ph('Vörösszárnyú 3')],
      ),
      Halfaj(
        id: 'hal_08', nev: 'Karikakeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Tányér formájú, magas hátú, meglehetősen lapos hal. A dévérkeszegnél kisebb termetű marad, pikkelyei nagyobbak, szeme feltűnően nagy, uszonyai pedig világosak, gyakran narancsos-pirosas tövűek. Elsősorban lassan áramló folyókban, csatornákban és öreg tavakban él. Étlapján planktonok, apró iszaplakók szerepelnek. Hagyományos sötétebb keszegező etetőanyagokkal, gilisztával, csontkukaccal jól fogható finom fenekező (feeder) vagy úszós készséggel, szinte egész évben.',
        kepek: [_ph('Karikakeszeg 1'), _ph('Karikakeszeg 2'), _ph('Karikakeszeg 3')],
      ),
      Halfaj(
        id: 'hal_09', nev: 'Jászkeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '20 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Testalkata a bodorkáéhoz hasonló, ám vaskosabb, pikkelyei pedig jóval apróbbak. A nagyobb példányok arany-bronzos fényt kapnak, az alsó uszonyok vörösek. Folyóvizeink jellegzetes hala, gyakran a felszín közelében vagy sebes sodrásban vadászik repülő rovarokra, sőt a nagyobb példányok áttérnek a ragadozó életmódra is (kishalakat esznek). Horgászható úszózva csontival, de nagyon népszerű a pergetőhorgászok körében is, mivel apró wobblerekre, körforgókra agresszívan rárabol.',
        kepek: [_ph('Jászkeszeg 1'), _ph('Jászkeszeg 2'), _ph('Jászkeszeg 3')],
      ),
      Halfaj(
        id: 'hal_10', nev: 'Laposkeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Neve tökéletesen leírja: rendkívül lapos, vékony testű hal, ferdén felfelé irányuló szájréssel és nagyon hosszú anális (alsó) úszóval. Szinte kizárólag a nyílt vízoszlopban, vízközt él, ahol apró zooplanktonokat szűröget. A nagyobb folyók és mély tavak nyílt vizeit kedveli. Speciális, lassan süllyedő, felhősítő etetőanyagokkal, hosszú előkés úszós (match) vagy feeder módszerrel fogható, csalinak apró pinki vagy szúnyoglárva a legjobb.',
        kepek: [_ph('Laposkeszeg 1'), _ph('Laposkeszeg 2'), _ph('Laposkeszeg 3')],
      ),
      Halfaj(
        id: 'hal_11', nev: 'Szilvaorrú keszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '20 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Szürkéskék háta és világos hasa van, de legjellegzetesebb vonása a húsos, kékes-lilás, "szilvára" emlékeztető duzzadt orr, ami alatt a szája mélyen alulról nyílik. Kifejezetten áramlatkedvelő hal, a folyók kavicsos, oxigéndús szakaszain érzi jól magát, ahol a paduChoz hasonlóan a fenékről gyűjtögeti az apró rovarokat és algát. Erős folyóvízi úszózással, fűszeres vagy sajtos ízvilágú etetővel, 1-2 szem csontival horogra csalható.',
        kepek: [_ph('Szilvaorrú 1'), _ph('Szilvaorrú 2'), _ph('Szilvaorrú 3')],
      ),
      Halfaj(
        id: 'hal_12', nev: 'Domolykó', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '25 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Hengeres testű, nagy fejű, sötét szegélyű vastag pikkelyekkel borított óvatos folyóvízi hal. Kifejezetten mindenevő: a vízbe hulló rovaroktól, a víz fölé hajló fákról potyogó gyümölcsökön (meggy, eperfa) át a kisebb halakig és békákig szinte bármit megeszik. Horgászata izgalmas cserkelést igényel. Évszaktól függően fogható természetes csalikkal (sajt, gyümölcsök, sáska, lótetű), illetve könnyű pergető felszereléssel apró, bogarat imitáló wobblerekre.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Squalius_cephalus_Prague_Vltava_1.jpg/800px-Squalius_cephalus_Prague_Vltava_1.jpg', _ph('Domolykó 2'), _ph('Domolykó 3')],
      ),
      Halfaj(
        id: 'hal_13', nev: 'Garda', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '20 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '04.15 - 05.31.', szabalyozasEve: '2024',
        megjegyzes: 'Kardszerűen lapos testű, nagy pikkelyes, hajlott oldalvonalú balatoni és folyóvízi hal. A "látott hal", ahogy Tihanyban hívják, hatalmas csapatokban vonul. Felső állású szájával ragadozó életmódot is folytat a nyílt vízen rabolva az apróhal-rajokra. Élő csontival süllyedő úszóval ("gardázó úszó"), vagy balinhoz hasonlóan apró, villogó műcsalikkal, műléggyel pergetve fogják elsősorban a Balaton mólóin és a folyók kőgátjainál.',
        kepek: [_ph('Garda 1'), _ph('Garda 2'), _ph('Garda 3')],
      ),
      Halfaj(
        id: 'hal_14', nev: 'Csuka', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '40 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '02.01 - 03.31.', szabalyozasEve: '2024',
        megjegyzes: 'Testalkata nyílvesszőre emlékeztet, hátra tolt hátúszója páratlan gyorsulást biztosít számára. Zöldes-sárgás, foltos márványozott színe tökéletesen álcázza a hínáros, nádas részeken. Hatalmas, lapos "kacsacsőr" szájában több száz hátrahajló, borotvaéles fog ül. Lesből vadászó ragadozó, villámgyorsan rabol kishalra, békára. Horgászatánál kötelező a harapásálló (drót, wolfram, vastag fluorocarbon) előke használata! Élő vagy döglött kishallal úszózva, illetve élénk színű műcsalik (támolygó villantó, wobbler, gumihal) húzásával fogható.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Esox_lucius_Prague_Vltava_1.jpg/800px-Esox_lucius_Prague_Vltava_1.jpg', _ph('Csuka 2'), _ph('Csuka 3')],
      ),
      Halfaj(
        id: 'hal_15', nev: 'Süllő (Fogas)', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '30 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '03.01 - 04.30.', szabalyozasEve: '2024',
        megjegyzes: 'Nyúlánk, elegáns, ezüstös testű hal sötét, függőleges sávokkal. Feje hegyes, állkapcsában hatalmas, kiálló "ebfogak" találhatók, melyekkel biztosan ragadja meg a zsákmányt. Fénykerülő, kiváló látású hal, nappal a mederfenék mélyebb, akadós (fákkal, kövekkel teli) részein tartózkodik, és inkább szürkületkor, éjszaka vadászik a parti sávokban. Fenekezve fűzött, taposott kishallal, vagy gumihalakkal, wobblerekkel pergetve fogható. A 1,5 kg feletti balatoni példányokat hagyományosan "fogasnak" hívják.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Sander_lucioperca_1.jpg/800px-Sander_lucioperca_1.jpg', _ph('Süllő 2'), _ph('Süllő 3')],
      ),
      Halfaj(
        id: 'hal_16', nev: 'Kősüllő', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '25 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '03.01 - 06.30.', szabalyozasEve: '2024',
        megjegyzes: 'Megjelenése nagyban hasonlít a süllőére, de zömökebb marad, a sötét sávjai ("párducminta") sokkal határozottabbak, és a szájából hiányoznak a hatalmas ebfogak. Sokkal érzékenyebb az oxigénhiányra és a vízminőségre. Figyelem: tilalmi ideje jelentősen hosszabb, mint a rokonáé! Tápláléka zömmel apró halakból és lárvákból áll. Finom pergetéssel, kisméretű plasztik csalikkal, vagy vékony gilisztával és apró taposott kishallal fogható kövezések környékén.',
        kepek: [_ph('Kősüllő 1'), _ph('Kősüllő 2'), _ph('Kősüllő 3')],
      ),
      Halfaj(
        id: 'hal_17', nev: 'Harcsa (Európai)', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '60 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '05.02 - 06.15.', szabalyozasEve: '2024',
        megjegyzes: 'Vizeink vitathatatlan csúcsragadozója és legnagyobb méretű hala (akár a 100 kilót is meghaladhatja). Teste pikkelytelen, nyálkás, feje lapos, szájánál két hosszú, a tájékozódást segítő bajuszszál, alul pedig négy rövidebb található. Nappal a fenéken, gödrökben, bedőlt fák alatt rejtőzik, éjjel indul rabolni, szájával "kluttyanó" hangot adva beszippantja zsákmányát (halak, békák, vízimadarak). Erős, nagy teherbírású felszereléssel, élő kárásszal, nadállyal, piócacsokorral, vagy nagyméretű wobblerekkel pergetve és a speciális "kuttyogató" módszerrel horgásszák. (100 cm feletti példány tilalom idején is vihető).',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Silurus_glanis_01.jpg/800px-Silurus_glanis_01.jpg', _ph('Harcsa 2'), _ph('Harcsa 3')],
      ),
      Halfaj(
        id: 'hal_18', nev: 'Balin', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '40 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '03.01 - 04.30.', szabalyozasEve: '2024',
        megjegyzes: 'Különleges fajunk: a pontyfélékhez tartozik (ezért egyetlen foga sincs, csak garatfoga), mégis ízig-vérig ragadozó életmódot folytat. Torpedó alakú, ezüstös testével, mélyen hasított szájával valóságos sebességbajnok. Csapatosan vonuló küszökre rabol, a felszínen hatalmas, robbanásszerű fröcskölésekkel veri szét a rajokat. Horgászata rendkívül látványos: gyors tempóban tekert, a felszín alatt vezetett ezüstös műcsalikkal (ólomfejes woblerek, balinólmok, támolygók) lehet becsapni.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Aspius_aspius_Prague_Vltava_1.jpg/800px-Aspius_aspius_Prague_Vltava_1.jpg', _ph('Balin 2'), _ph('Balin 3')],
      ),
      Halfaj(
        id: 'hal_19', nev: 'Sügér (Csapósügér)', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '15 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '03.01 - 04.30.', szabalyozasEve: '2024',
        megjegyzes: 'Gyönyörű, zöldes-aranyos színezetű, testén fekete, függőleges "tigriscsíkokkal" díszített ragadozó. Első hátúszójának végén fekete folt van, a tüskéi szúrósak, has- és farokúszója élénk narancs-piros. Csapatosan, a kövek, mólók, nádszélek árnyékában leselkedik apróhalakra és férgekre. Ultra-light pergetéssel (mikrojigek, apró gumihalak, körforgók) és vékony gilisztával, csontkukaccal úszózva roppant szórakoztató, könnyen fogható célhal.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Perca_fluviatilis_Prague_Vltava_1.jpg/800px-Perca_fluviatilis_Prague_Vltava_1.jpg', _ph('Sügér 2'), _ph('Sügér 3')],
      ),
      Halfaj(
        id: 'hal_20', nev: 'Menyhal', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '25 cm', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: '01.01 - 02.28.', szabalyozasEve: '2024',
        megjegyzes: 'A tőkehalfélék egyetlen édesvízi, hazánkban is élő képviselője. Kígyószerű, lapított fejű, barna-márványos mintázatú hal, alsó állkapcsán egyetlen jellegzetes, hosszú bajuszszállal. Kizárólag a téli, hideg vizű folyókban aktív (a nyarat kövek alatt "nyári álmot" aludva tölti). Télen sötétedés után, a fagyos éjszakákban vadászik. Taposott kishallal, halszelettel, gilisztával horgásznak rá egyszerű csúszóólmos fenekező készséggel, sziklás-köves folyószakaszokon.',
        kepek: [_ph('Menyhal 1'), _ph('Menyhal 2'), _ph('Menyhal 3')],
      ),
      Halfaj(
        id: 'hal_21', nev: 'Amur', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Kínából betelepített, hatalmas torpedó alakú, nagy, ezüstös-zöldes pikkelyű hal. Feje széles, szája előre néz. Kifejezetten növényevő: hihetetlen mennyiségű hínárt, nádat képes elfogyasztani naponta. Nagyon melegkedvelő. Erjesztett (büdös) fokhagymás vagy tejsavas kukoricával, lucernás pelletekkel fogható. Kapása csendes, a parthoz érve azonban robbanásszerűen, hihetetlen nyers erővel kezd védekezni, ami miatt különösen masszív felszerelést igényel.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ctenopharyngodon_idella.jpg/800px-Ctenopharyngodon_idella.jpg', _ph('Amur 2'), _ph('Amur 3')],
      ),
      Halfaj(
        id: 'hal_22', nev: 'Afrikai harcsa', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Hőkedvelő, telepített tavi ragadozó. Teste csupasz, nyálkás, feje hatalmas, kemény csontlemezes, 8 bajuszszála van. Különleges légzőszerve révén az iszapos, oxigénhiányos vizet is bírja, akár a felszínen is pipál. Rendkívül falánk mindenevő: halszelet, büdös máj, csirkebél, nadály, de az ízesített halas pelletek is a kedvencei. Fogása nyáron intenzív tavakon a legbiztosabb. Keményen küzd, rázza a fejét a horgon.',
        kepek: [_ph('Afrikai harcsa 1'), _ph('Afrikai harcsa 2'), _ph('Afrikai harcsa 3')],
      ),
      Halfaj(
        id: 'hal_23', nev: 'Tokhal (Hibridek)', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Intenzív telepítésű horgásztavakon elterjedt, cápára emlékeztető ősi hal. Testén csontos vért-sorok futnak, orra megnyúlt, alatta 4 bajuszszál és harmonikaszerű, kinyújtható száj található. Fenékről táplálkozik, szag alapján keres. Erős, halas-büdös etetőanyagokkal, főként süllyedő Halibut (laposhal) pelletekkel fogható. Fárasztáskor rendkívül erős, gyakran kiugrik a vízből, kifogás után azonnali és óvatos visszaengedést igényel a horgásztavakon.',
        kepek: [_ph('Tokhal (Hibrid) 1'), _ph('Tokhal 2'), _ph('Tokhal 3')],
      ),
      Halfaj(
        id: 'hal_24', nev: 'Fekete amur', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Testalkata az amurhoz hasonló, de pikkelyei és uszonyai jóval sötétebbek, kifejezetten szürkés-feketések. Míg az amur növényt eszik, a fekete amur tápláléka szinte kizárólag puhatestűekből áll: garatfogaival könnyedén roppantja szét a kagylók, vándorkagylók és csigák mészvázát. Horgászata során is ezt érdemes figyelembe venni: leginkább zöldkagylós (GLM - Green Lipped Mussel) bojlikkal, kagylóhússal lehet kapásra bírni.',
        kepek: [_ph('Fekete amur 1'), _ph('Fekete amur 2'), _ph('Fekete amur 3')],
      ),
      Halfaj(
        id: 'hal_25', nev: 'Buffalo (Nagyszájú buffalo)', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Észak-Amerikából származó, Magyarországon csak néhány intenzív tóban jelen lévő faj. Formára leginkább egy hatalmas, vastag kárász és a busa keverékére emlékeztet, nagy fejjel és tágas, felfelé irányuló szájjal. Planktonszűrő életmódot folytat, de az iszapban is turkál szerves törmelék után. Pontyozó felszereléssel, édes-gyümölcsös bojlikkal, pelletekkel esetenként megfogható békés hal.',
        kepek: [_ph('Buffalo 1'), _ph('Buffalo 2'), _ph('Buffalo 3')],
      ),
      Halfaj(
        id: 'hal_26', nev: 'Sebes pisztráng', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: '22 cm', darabKorlatozas: '3 db/nap', tilalmiIdoszak: '10.01 - 03.31.', szabalyozasEve: '2024',
        megjegyzes: 'Hegyi és dombvidéki, gyors folyású, hideg, oxigéndús patakjaink csodálatos, őshonos ragadozója. Háta sötétbarna vagy zöldes, oldalán fekete és világos udvarral körülvett, élénk piros pettyek találhatók. Rovarokra, lárvákra, kifejletten apró halakra rabol, folyamatosan az áramlatokkal szemben úszva. Szigorú szabályozás mellett, általában csak mesterséges műcsalival (pergetve apró körforgó villantóval, apró gumival) vagy legyező horgászattal ejthető el.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Salmo_trutta_fario_in_Genoa.jpg/800px-Salmo_trutta_fario_in_Genoa.jpg', _ph('Sebes pisztráng 2'), _ph('Sebes pisztráng 3')],
      ),
      Halfaj(
        id: 'hal_27', nev: 'Szivárványos pisztráng', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Észak-Amerikából származó, tógazdaságokban és hűvösebb horgásztavakban gyakran telepített faj. Testét sűrű fekete pettyek borítják, oldalán pedig egy jellegzetes, irizáló, rózsaszínes-lilás "szivárvány" sáv fut végig. Jobban tűri a felmelegedő vizet a sebes pisztrángnál. Ultra light pergetéssel, apró kanálvillantókkal (trout area horgászat), műléggyel, vagy úszós-sbirolinós módszerrel és speciális lebegő pisztrángpasztával fogják.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Oncorhynchus_mykiss_01.jpg/800px-Oncorhynchus_mykiss_01.jpg', _ph('Szivárványos 2'), _ph('Szivárványos 3')],
      ),
      Halfaj(
        id: 'hal_28', nev: 'Pisztrángsügér (Black Bass)', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Amerikai eredetű, a világ egyik legnépszerűbb sportfala. Zömök testű, zöldes-olív színű, a háti részén márványos mintával. Hatalmasra nyitható szája van. Imádja a fedezékeket, a vízinövényzet és bedőlt fák sűrűjéből csap le áldozataira. Hazánkban kevés vízben található meg (pl. Kiskunlacháza, egyes bányatavak). Texas/Carolina riggel vezetett gumirákokkal, felszíni békákkal és popperekkel hatalmas élmény a horgászata.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Micropterus_salmoides.jpg/800px-Micropterus_salmoides.jpg', _ph('Pisztrángsügér 2'), _ph('Pisztrángsügér 3')],
      ),
      Halfaj(
        id: 'hal_29', nev: 'Pettyes harcsa', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Az afrikai és törpeharcsához némileg hasonló, Amerikából behurcolt faj. Bőre pikkelytelen, színe világosabb szürkés-barnás, oldalán apró, sötét pettyekkel. Farokúszója a szürkeharcsáéval ellentétben mélyen villás (kétlebenyű). Főleg meleg vizű, intenzív tavakban él, ahol fenekező felszereléssel, halas pelletekkel, büdös májjal vagy gilisztacsokorral könnyen megfogható falánk hal.',
        kepek: [_ph('Pettyes harcsa 1'), _ph('Pettyes harcsa 2'), _ph('Pettyes harcsa 3')],
      ),
      Halfaj(
        id: 'hal_30', nev: 'Csíkos sügér', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Hazánkban ritka, kizárólag néhány zárt rendszerű hűtőtóban (pl. Lőrinci) élő amerikai ragadozó. Teste ezüstös, melyen hosszanti, sötét, párhuzamos csíkok futnak végig a fejétől a farkáig. Nyílt vízen, csapatosan hajtja a kishalakat (mint a balin). Horgászata élő kishallal úszózva, vagy áramvonalas pergető műcsalik, vertikális jigek használatával lehetséges.',
        kepek: [_ph('Csíkos sügér 1'), _ph('Csíkos sügér 2'), _ph('Csíkos sügér 3')],
      ),
      Halfaj(
        id: 'hal_31', nev: 'Lapátorrú tok', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Észak-Amerikából származó különlegesség, teste cápaszerű, de a legfeltűnőbb része a hatalmas, lapos, evezőlapát formájú orr-része. Nyitott szájjal úszik a vízközt, és kizárólag a lebegő apró zooplanktont szűri ki, mint a bálnák. Mivel nem rág rágcsálnivalót, és nem eszik fenékről, hagyományos horgászmódszerekkel, csalival szinte képtelenség megfogni; a horogra akadása legtöbbször csak véletlen külső akadás a planktonfelhőben.',
        kepek: [_ph('Lapátorrú tok 1'), _ph('Lapátorrú tok 2'), _ph('Lapátorrú tok 3')],
      ),
      Halfaj(
        id: 'hal_32', nev: 'Aranyhal', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Tudományosan az ezüstkárász ázsiai színmutációja. Kerti tavakból szabadult, vagy illegálisan betelepített példányai élnek vad vizeinkben. A legszembetűnőbb a narancssárga, arany, esetenként tarka pikkelyzete. Viselkedése, élőhely-igénye és táplálkozása teljes mértékben megegyezik a közönséges kárászéval. Finomszerelékes úszózással, csontkukacra és csemegekukoricára könnyen megfogható.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Goldfish_in_aquarium.jpg/800px-Goldfish_in_aquarium.jpg', _ph('Aranyhal 2'), _ph('Aranyhal 3')],
      ),
      Halfaj(
        id: 'hal_33', nev: 'Angolna', kategoria: 'Ragadozó', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Megjelenése egy kígyóéhoz hasonlít: extrém hosszú, pikkelytelen, rendkívül nyálkás és izmos teste van. Élete során hatalmas utat tesz meg: a Sargasso-tengerben ívik, majd az európai édesvizekbe vándorol felnőni. Éjszakai ragadozó, a fenéken megbújva vadászik rákokra, kishalakra és dögökre. Földigilisztával, halszelettel sötétedés után fenekezve fogható, de a kifogása után a nyálka miatt rendkívül nehéz megfogni, rácsavarodik az előkére.',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Anguilla_anguilla.jpg/800px-Anguilla_anguilla.jpg', _ph('Angolna 2'), _ph('Angolna 3')],
      ),
      Halfaj(
        id: 'hal_34', nev: 'Törpeharcsa', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Amerikából betelepített, rendkívül szívós, kártékony inváziós hal. Színe sötétbarna, sárgás hasi résszel, feje lapos, 8 bajuszszála van. A mell- és hátúszóiban csontos, fűrészes bognártüske található, ami fájdalmas szúrást tud ejteni! Minden élőhelyen tömegesen szaporodik, elpusztítva az őshonos halak ikráit és ivadékait. Rendkívül mohó, a fenéken mindent – gilisztát, kukoricát, pelletet – azonnal mélyre nyel. Fogása esetén a vízbe visszaengedni szigorúan tilos!',
        kepek: [_ph('Törpeharcsa 1'), _ph('Törpeharcsa 2'), _ph('Törpeharcsa 3')],
      ),
      Halfaj(
        id: 'hal_35', nev: 'Ezüstkárász', kategoria: 'Békés', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Keletről behurcolt, szürke/ezüstös színű, zömök testű, nagy pikkelyes hal. Nincs bajuszszála (ez különbözteti meg a kispontytól). Szaporodásbiológiája miatt más halak (pl. ponty) spermája is kiváltja az ikrái sejtosztódását, így klónként szaporodik, hatalmas túlnépesedést okozva és kiszorítva az őshonos széles kárászt. Bármely klasszikus békéshalas csalival (kukorica, pellet, giliszta) könnyen fogható. Inváziós faj lévén, kifogása után visszaengedni tilos!',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Carassius_gibelio_2008_G1.jpg/800px-Carassius_gibelio_2008_G1.jpg', _ph('Ezüstkárász 2'), _ph('Ezüstkárász 3')],
      ),
      Halfaj(
        id: 'hal_36', nev: 'Busa (Fehér és Pettyes)', kategoria: 'Békés', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Kínából betelepített, hatalmasra, akár 40-50 kilósra is megnövő ezüstös hal. Feje testéhez képest aránytalanul nagy, szemei mélyen, a szája vonala alatt ülnek. Hatalmas kopoltyúival a vízben lebegő mikroszkopikus növényi (fitoplankton) és állati (zooplankton) szervezeteket szűri. Hagyományos csalival ritkán fogható. Célzott horgászata hatalmas, vízközt lebegő etetőanyag-felhőt képező "technoplankton" tablettákkal és lebegtetett hungarocell (pufi) csalival történik. Inváziós faj, visszaengedni tilos!',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Hypophthalmichthys_nobilis.jpg/800px-Hypophthalmichthys_nobilis.jpg', _ph('Busa 2'), _ph('Busa 3')],
      ),
      Halfaj(
        id: 'hal_37', nev: 'Kecsege', kategoria: 'Békés', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Magyarország egyik legkülönlegesebb őshonos hala, a Duna és a Tisza lakója. Cápaszerű, nyújtott teste van, pikkelyek helyett csontos vért-sorok védik. Orra hegyes, felkunkorodó, alul négy rojtos bajuszszállal. Fenékporszívóként kérészeket, lárvákat gyűjt. Korábban népszerű horgászhal volt, azonban állománycsökkenése miatt természetes vizeken jelenleg nem fogható (kivéve speciális, éves kutatási-horgász engedéllyel). Ha horogra akad gilisztázás közben, azonnal kíméletesen vissza kell engedni!',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Acipenser_ruthenus.jpg/800px-Acipenser_ruthenus.jpg', _ph('Kecsege 2'), _ph('Kecsege 3')],
      ),
      Halfaj(
        id: 'hal_38', nev: 'Széles kárász (Aranykárász)', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Őshonos "arany" kárászunk régen a mocsarak leggyakoribb hala volt. Rendkívül magas hátú, zömök testű, sötét, arany-bronzos-barnás pikkelyzettel rendelkezik. Hátúszója kifelé domborodó (az ezüstkárászé befelé homorú). A leghihetetlenebb iszapos, oxigénszegény körülményeket is túléli. Az élettér szűkülése és az ezüstkárász terjedése miatt súlyosan megfogyatkozott. Ma már fokozottan védett faj, horgászata és megtartása szigorúan tilos!',
        kepek: ['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carassius_carassius_Prague_Vltava_1.jpg/800px-Carassius_carassius_Prague_Vltava_1.jpg', _ph('Széles kárász 2'), _ph('Széles kárász 3')],
      ),
      Halfaj(
        id: 'hal_39', nev: 'Leánykoncér', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Tiszta vizű, gyorsabb folyóink (pl. Duna, Rába) nyúlánk, hengeres testű, ezüstös lakója. Testalkata leginkább a domolykó és a paduc keverékére hasonlít, de az orra tompább. Kifejezetten áramlatkedvelő faj, rovarokat, csigákat fogyaszt a köves mederfenékről. Természetvédelmi értéke miatt szigorúan védett faj, fogása esetén nedves kézzel, a lehető leggyorsabban vissza kell juttatni a folyóba.',
        kepek: [_ph('Leánykoncér 1'), _ph('Leánykoncér 2'), _ph('Leánykoncér 3')],
      ),
      Halfaj(
        id: 'hal_40', nev: 'Koi ponty', kategoria: 'Békés', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A közönséges ponty Japánban kitenyésztett díszhal (színmutáció) változata. A narancssárga, fehér, piros és fekete foltok legkülönbözőbb mintázatait viselheti magán. Mivel anatómiailag azonos a ponttyal, a táplálkozása és viselkedése is megegyezik vele. Hazai horgásztavakon gyakori telepített hal, kifogása szerencsét hoz, de horgászatilag ugyanúgy bojlikkal, pellettel és kukoricával ejthető el, mint sima társai.',
        kepek: [_ph('Koi ponty 1'), _ph('Koi ponty 2'), _ph('Koi ponty 3')],
      ),
      Halfaj(
        id: 'hal_41', nev: 'Magyar bucó', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Különleges megjelenésű, kifejezetten fenéklakó, őshonos folyóvízi halunk. Teste erősen megnyúlt, hengeres, a feje felülről lapított. Alapszíne sárgás-barnás, a hátán 3-4 sötét, széles, ferde, nyeregszerű sáv fut le az oldalára. Teljesen az áramlatos aljzathoz lapulva vadászik apró férgekre és rákokra. Endemikus (csak a Kárpát-medencében élő), fokozottan védett természeti kincsünk.',
        kepek: [_ph('Magyar bucó 1'), _ph('Magyar bucó 2'), _ph('Magyar bucó 3')],
      ),
      Halfaj(
        id: 'hal_42', nev: 'Német bucó', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A magyar bucó közeli rokona, szintén gyors áramlású folyók kavicsos mederfenekén él. Teste zömökebb és rövidebb a magyar bucóénál, a hasi része fehér, míg az oldala halványbarna. Szintén rovarlárvákkal és apró gerinctelenekkel táplálkozik. Ritkuló állománya miatt szigorú védelmet élvez, horogra akadása esetén azonnali szabadon engedést igényel.',
        kepek: [_ph('Német bucó 1'), _ph('Német bucó 2'), _ph('Német bucó 3')],
      ),
      Halfaj(
        id: 'hal_43', nev: 'Tarka géb', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Az egyetlen gébféle, amely régebb óta honos vizeinkben, a folyók partszéli, köves, sekély szakaszain érzi jól magát. Barnás-tarkás mintázatú, és nagyon hasonlít a később behurcolt inváziós gébekre (pl. folyami géb). Megkülönböztető jele az orrnyílásaiból kinyúló 1-2 mm-es, apró porcos "csövecske". Mivel az inváziós rokonai miatt élőhelye drasztikusan szűkült, védett fajjá nyilvánították.',
        kepek: [_ph('Tarka géb 1'), _ph('Tarka géb 2'), _ph('Tarka géb 3')],
      ),
      Halfaj(
        id: 'hal_44', nev: 'Réti csík', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Igazi mocsári túlélőművész! Sárgásbarna, hosszanti sötét csíkokkal díszített, kígyószerűen megnyúlt testű, nagyon nyálkás hal, melynek 10 apró bajuszszála van. Víziközlekedése és béllégzése révén a kiszáradó mocsarakat, oxigénszegény ártereket is átvészeli iszapba ásva. Mára az élőhelyei radikálisan lecsökkentek, így fokozott védelem alatt áll. Megtartani és csalihalként használni szigorúan tilos.',
        kepek: [_ph('Réti csík 1'), _ph('Réti csík 2'), _ph('Réti csík 3')],
      ),
      Halfaj(
        id: 'hal_45', nev: 'Vágó csík', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Hasonló a réti csíkhoz, de teste oldalról jóval lapítottabb, színezete élénkebb sárga, nagy, négyszögletes sötét foltokkal. Különlegessége a szeme alatt található felmereszthető kis csonttüske (erről kapta a "vágó" nevet). Tiszta vizű patakok homokos, iszapos fenekén él, ahová veszély esetén nyomtalanul be tud fúrni. Védett állatunk.',
        kepek: [_ph('Vágó csík 1'), _ph('Vágó csík 2'), _ph('Vágó csík 3')],
      ),
      Halfaj(
        id: 'hal_46', nev: 'Pénzes pér', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A lazacfélék családjába tartozó, hegyi folyókban és patakokban élő lenyűgöző hal. Nevét ezüstösen csillogó, pénzérmére emlékeztető pikkelyeiről kapta. Legfeltűnőbb ékessége a hatalmas, vitorlaszerű, narancssárga-lilás pöttyökkel tarkított hátúszója. Vízbe hulló rovarokkal táplálkozik, ezért a legyező horgászok nagy álma, azonban Magyarországon rendkívül ritka és fokozottan védett.',
        kepek: [_ph('Pénzes pér 1'), _ph('Pénzes pér 2'), _ph('Pénzes pér 3')],
      ),
      Halfaj(
        id: 'hal_47', nev: 'Lápi póc', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Mindössze 8-10 centisre megnövő, mocsarakban, tőzeges vizekben élő endemikus (csak a Kárpát-medencében élő) apróhal. Teste csokoládébarna, hasa világos, farokúszója lapát formájú, lekerekített. Hatalmas szája a kis méretéhez képest sokat elárul ragadozó életmódjáról (lárvákat eszik). A csatornák kotrása és élőhelyeinek pusztulása miatt ma már a legfokozottabban védett halaink közé tartozik.',
        kepek: [_ph('Lápi póc 1'), _ph('Lápi póc 2'), _ph('Lápi póc 3')],
      ),
      Halfaj(
        id: 'hal_48', nev: 'Viza', kategoria: 'Ragadozó', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Minden idők legnagyobb édesvízi halfaja, a tokfélék "királya". Hossza elérheti a 8-9 métert, súlya a tonnát is! Anadrom hal, azaz a tengerből úszott fel a Dunába ívni (régen a Vaskapu előtt a Duna tele volt velük). Hatalmas, hússzínű orra, és porcos vértjei vannak. Az erőművek és gátak építése miatt a felvonulási útvonaluk elzáródott, így a hazai vizekből szinte teljesen eltűnt. Szigorúan védett és megőrzendő faj.',
        kepek: [_ph('Viza 1'), _ph('Viza 2'), _ph('Viza 3')],
      ),
      Halfaj(
        id: 'hal_49', nev: 'Vágó tok', kategoria: 'Békés', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Hazánk egyik őshonos, folyóvízi (dunai és tiszai) tokféléje. Karcsú teste, megnyúlt orra és 5 sorban futó éles, csontos pajzsok (vértek) jellemzik. Orra hegye kissé felfelé hajlik. Áramlatkedvelő fenéklakó hal, férgeket és apró kagylókat szívogat a mederből. Mivel állománya kritikusan megfogyatkozott, ma már egész évben tilos kifogni és megtartani.',
        kepek: [_ph('Vágó tok 1'), _ph('Vágó tok 2'), _ph('Vágó tok 3')],
      ),
      Halfaj(
        id: 'hal_50', nev: 'Sima tok', kategoria: 'Békés', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Egy másik ősi tokfélénk, formájában a vágó tokhoz hasonlít, de teste zömökebb, orra tompább és lekerekítettebb, valamint a testét borító vértek sokkal kevésbé élesek, jobban belesimulnak a bőrbe (innen a "sima" név). Nagyon ritka kóborló a hazai nagy folyókban, szigorú állományvédelem alatt áll. Fogása esetén a vízben tartva, a lehető leghamarabb meg kell szabadítani a horogtól.',
        kepek: [_ph('Sima tok 1'), _ph('Sima tok 2'), _ph('Sima tok 3')],
      ),
      Halfaj(
        id: 'hal_51', nev: 'Sőregtok', kategoria: 'Ragadozó', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A tokfélék között az egyik leglátványosabb csillag formájú hátvértekkel rendelkezik, és orra is kard formájú, hosszúra nyúlt. Eredetileg a tengerben él, és a nagy folyókba csak ikrázni vonul fel. A dunai erőművek miatt mára hazánkban a kipusztulás szélére került ritkaság. Természetvédelmi oltalom alatt áll, horgászata semmilyen formában nem megengedett.',
        kepek: [_ph('Sőregtok 1'), _ph('Sőregtok 2'), _ph('Sőregtok 3')],
      ),
      Halfaj(
        id: 'hal_52', nev: 'Vágó durbincs', kategoria: 'Ragadozó', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A sügérrel rokon, pici (10-15 cm-es) tüskés, zöldes-barnás, apró fekete pettyekkel mintázott hal. Hátúszójának első sugaraiban hegyes tüskék vannak. Hazai folyók csendesebb szakaszain, és az öreg tavak parti zónáiban csapatokba verődve eszik a fenéken a gilisztákat és szúnyoglárvákat. Bár nagyon falánk és gyakran idegesíti a horgászokat, állományvédelmi okok miatt ma már tilos megtartani vagy csalihalként használni.',
        kepek: [_ph('Vágó durbincs 1'), _ph('Vágó durbincs 2'), _ph('Vágó durbincs 3')],
      ),
      Halfaj(
        id: 'hal_53', nev: 'Selymes durbincs', kategoria: 'Ragadozó', statusz: 'Nem fogható',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Megjelenésében nagyon hasonlít a vágó durbincsra, de ahogy a neve is sejteti, a feje lágyabb, tapintásra selymesebb, nincsenek rajta mély gödröcskék, pikkelyei pedig halványabb sárgák. Kifejezetten a gyorsabb folyóvizeket, homokos, sóderes aljzatot kedveli, ahol bolharákokra vadászik. Szintén tilalom alatt álló, megőrzendő fajunk.',
        kepek: [_ph('Selymes durbincs 1'), _ph('Selymes durbincs 2'), _ph('Selymes durbincs 3')],
      ),
      Halfaj(
        id: 'hal_54', nev: 'Feketeszájú géb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A Fekete-tenger és a Kaszpi-tenger vidékéről a folyami hajózással behurcolt, agresszíven terjeszkedő inváziós apróhal. Jellemzője a viszonylag nagy fej, a dülledt béka-szemek és a hímek koromfekete szája. Irtózatos pusztítást végez az őshonos halak ikrái és ivadékai között a kövezések mentén. Rendkívül mohó, gilisztával pillanatok alatt fogható. Törvény kötelez rá, hogy kifogása esetén tilos a vízbe visszaengedni!',
        kepek: [_ph('Feketeszájú géb 1'), _ph('Feketeszájú géb 2'), _ph('Feketeszájú géb 3')],
      ),
      Halfaj(
        id: 'hal_55', nev: 'Csupasztorkú géb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Egy újabb betolakodó gébféle. Különlegessége, hogy a kopoltyúrése alatti torokrészen (a hasi oldalon) egyáltalán nincsenek pikkelyek. Színe álcázó világos homokszínű vagy barnás foltos. Szintén a kövezések, mólók alján bujkál, és mohón felfal minden útjába kerülő férget vagy halikrát. Mivel inváziós károsító, kifogás után nem szabad visszaengedni a vízbe.',
        kepek: [_ph('Csupasztorkú géb 1'), _ph('Csupasztorkú géb 2'), _ph('Csupasztorkú géb 3')],
      ),
      Halfaj(
        id: 'hal_56', nev: 'Kessler-géb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A hazai vizekben előforduló inváziós gébfélék közül a legnagyobbra növő faj. Lapos, széles "varangy" feje van, és aránytalanul nagy szája. Színezete sötét márványos, gyakran vöröses tónussal a hátúszón. Nem csak az ikrát eszi meg, de félelmetes ragadozóként az apróhalakat is elkapja a fenéken. Tilos a visszaengedése!',
        kepek: [_ph('Kessler-géb 1'), _ph('Kessler-géb 2'), _ph('Kessler-géb 3')],
      ),
      Halfaj(
        id: 'hal_57', nev: 'Szélhajtó küsz (Sneci)', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A vízfeszínen ezüstösen csillogó, szüntelenül mozgó "sneci" vizeink legelterjedtebb apróhala. Háta kékes-zöld, teste torpedó alakú, szája felső állású, hogy a vízre hulló apró rovarokat és planktonokat könnyen összeszedje. A balin és a süllő legfőbb természetes tápláléka, ezért a horgászok körében a legnépszerűbb csalihal. Horgászata finom 1-2 méteres spiccbotokkal, pici úszóval és 1 szem csontival zajlik.',
        kepek: [_ph('Szélhajtó küsz 1'), _ph('Szélhajtó küsz 2'), _ph('Szélhajtó küsz 3')],
      ),
      Halfaj(
        id: 'hal_58', nev: 'Bagolykeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A dévérkeszeggel rokon, de sokkal nyúlánkabb, elnyújtott testalkatú keszeg. Pikkelyei nagyobbak, és a dévérhez képest vastagabb testű hal. Nevét onnan kapta, hogy szeme hatalmas, "bagolyszerű". Áramlatkedvelő faj, főleg a nagyobb, tiszta vizű folyóink mederfenekén alkot sűrű rajokat. Fogási esélyeit a sajtos vagy mogyorós etetőanyag, és a feeder technikával felkínált csonti/giliszta növeli.',
        kepek: [_ph('Bagolykeszeg 1'), _ph('Bagolykeszeg 2'), _ph('Bagolykeszeg 3')],
      ),
      Halfaj(
        id: 'hal_59', nev: 'Lánykeszeg', kategoria: 'Békés', statusz: 'Fogható (Őshonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs (egyéb hal)', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Küllemében nagyon hasonlít a paducra és a szilvaorrú keszegre. Alsó állású szája kicsi, félhold alakú. Hátúszója magasan ívelt. A folyóvizek sóderes, homokos aljzatát kedveli, ahonnan algákat, bolharákokat csipeget fel. Jellemzően a paduc-rajok szélén tűnik fel, így horgászata is a klasszikus folyóvízi, erősen visszatartott úszós szerelékkel, és kenyér- vagy csonti csalival eredményes.',
        kepek: [_ph('Lánykeszeg 1'), _ph('Lánykeszeg 2'), _ph('Lánykeszeg 3')],
      ),
      Halfaj(
        id: 'hal_60', nev: 'Naphal', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Díszhalként Európába került, Észak-Amerikai ragadozó. Bár apró (tányér alakú) hal, megjelenése lenyűgöző: teste neonkék, zöld és sárga foltokban irizál, kopoltyúfedője végén pedig egy határozott "fül", egy piros-fekete folt látható. Extrém agresszív kis hal, minden apró rákot, rovart, kishalat és halikrát felfal a nádasok, hínárosok szélén. Egy szál gilisztával nagyon könnyű fogni, de inváziós jellege miatt tilos visszaengedni a magyar vizekbe!',
        kepek: [_ph('Naphal 1'), _ph('Naphal 2'), _ph('Naphal 3')],
      ),
      Halfaj(
        id: 'hal_61', nev: 'Kínai razbóra', kategoria: 'Békés', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Rendkívül szívós, apró termetű (5-8 cm-es) Ázsiából véletlenül behurcolt halacska. Teste ezüstös-sárgás, oldalán gyakran végigfut egy halvány sötét sáv. Felső állású apró szája van. Hihetetlenül gyorsan szaporodik, a partszéli sekély, nyugodt vizű részeken a csontit, gilisztát, pufit pillanatok alatt ellopja a horogról, tönkretéve a békéshalas horgászatot. Szintén inváziós károsító, amit nem szabad visszaengedni.',
        kepek: [_ph('Kínai razbóra 1'), _ph('Kínai razbóra 2'), _ph('Kínai razbóra 3')],
      ),
      Halfaj(
        id: 'hal_62', nev: 'Amurgéb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Kelet-Ázsiából származó sötétbarna, foltos, rejtőzködő színű betelepült gébféle. Kifejezetten ragadozó: hatalmas szájával elkapja a többi halfaj lárváit és kishalait a sekély, növényzettel dúsan benőtt (tavak, csatornák) részeken. Szaporodásuk során a hímek őrzik és gondozzák az ikrát, ezért állományuk rohamosan nő, drasztikusan irtva például az őshonos lápi pócokat. A kifogott példányokat szigorúan el kell pusztítani.',
        kepek: [_ph('Amurgéb 1'), _ph('Amurgéb 2'), _ph('Amurgéb 3')],
      ),
      Halfaj(
        id: 'hal_63', nev: 'Szivárványos ökle', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Káprázatos színekben pompázó, kisméretű pontyféle. A hímek nászidőszakban lilás-kékes-pirosas (szivárványos) árnyalatot öltenek magukra. Szaporodásuk biológiai csoda: a nőstény egy hosszú tojócső segítségével egyenesen egy élő tavi vagy tavikagyló (Anodonta) köpenyüregébe rakja le ikráit, így a kagyló megvédi a fejlődő halakat. Éppen a kagylók visszaszorulása miatt vált mára súlyosan veszélyeztetetté, és szigorúan védett fajjá.',
        kepek: [_ph('Szivárványos ökle 1'), _ph('Szivárványos ökle 2'), _ph('Szivárványos ökle 3')],
      ),
      Halfaj(
        id: 'hal_64', nev: 'Galóca', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A Kárpát-medence legimpozánsabb, legnagyobb méretűre növő lazacféléje. Torpedó alakú, hihetetlenül izmos testét apró fekete kereszt alakú foltok tarkítják, feje robusztus. A hegyvidéki, rohanó folyók mélyebb részein leste a kishalakat. Hazánk vízrendszereinek megváltozása, az oxigénhiány és a szennyezések miatt mára végveszélybe került, így a "vizek párducát" horgászati szempontból is a legszigorúbb védelem illeti.',
        kepek: [_ph('Galóca 1'), _ph('Galóca 2'), _ph('Galóca 3')],
      ),
      Halfaj(
        id: 'hal_65', nev: 'Fenékjáró küllő', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Megjelenése egy mini márnára emlékeztet. 10-15 cm-es hengeres testű, sárgásbarna hal, oldalán 8-10 nagyobb, szabálytalan sötét folttal. A szája sarkában két apró bajuszszál fityeg. Kizárólag tiszta vizű, gyors folyású folyók (Duna, Rába) és patakok kavicsos aljzatán tapad a fenékhez rovarok után kutatva. Érzékeny a vízszennyezésre, így a vizek tisztaságának kiváló indikátora. Őshonos és védett!',
        kepek: [_ph('Fenékjáró küllő 1'), _ph('Fenékjáró küllő 2'), _ph('Fenékjáró küllő 3')],
      ),
      Halfaj(
        id: 'hal_66', nev: 'Kövi csík', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Áramvonalas, kifejezetten hegyi patakok és hideg folyók gyors vizében élő hal. Sárgásbarna testén apró, szabálytalan, sötét márványos mintázat fut végig, a szájnyílása körül pedig hat rövid bajuszszál található. Idejének nagy részét a kövek alatt, búvóhelyeken tölti (innen a neve). Élőhelyeinek szűkülése miatt ritka, fokozottan védett kárpáti faj.',
        kepek: [_ph('Kövi csík 1'), _ph('Kövi csík 2'), _ph('Kövi csík 3')],
      ),
      Halfaj(
        id: 'hal_67', nev: 'Fürge cselle', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Apró, 6-9 cm-es, de annál gyönyörűbb színekben pompázó pontyféle. Az oldala fémesen csillogó, a hátán sötét sáv fut végig. A hímek nászidőszakban a hasukon és az oldaluk alsó részén égőpiros-zöld színezetet vesznek fel. A hidegvizű hegyi patakok csendesebb, árnyékosabb öbleit kedveli, apró rovarokkal táplálkozik. Természetvédelmi értéke kimagasló, tilos kifogni!',
        kepek: [_ph('Fürge cselle 1'), _ph('Fürge cselle 2'), _ph('Fürge cselle 3')],
      ),
      Halfaj(
        id: 'hal_68', nev: 'Botos kölönte', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Különös kinézetű, lapos, széles fejű, szinte pikkelytelen halacska. Úszóhólyagja nincs, ezért nem is tud a vízben lebegni, egész életét a patakok, tiszta folyók köveihez lapulva tölti "fenéklakóként". Neve ellenére ügyes kis ragadozó, rejtőszíne mögül lesből elkapja az apró bolharákokat, lárvákat, sőt, más halak ivadékait is. Az oxigéndús hegyi vizek szigorúan védett lakója.',
        kepek: [_ph('Botos kölönte 1'), _ph('Botos kölönte 2'), _ph('Botos kölönte 3')],
      ),
      Halfaj(
        id: 'hal_69', nev: 'Fekete törpeharcsa', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Az "átlagos" törpeharcsával ellentétben ennek a fajnak a teste sötétebb, egyöntetű feketés-olív színű (nem márványos a minta). Észak-Amerikából származik, a meleg és oxigénszegény sekély vizekben (pl. tőzegtavak, kubikgödrök) képes elszaporodni elképesztő mértékben. Ikrapusztító inváziós kártevő, bognártüskéjének szúrása gennyesedő sebet okozhat. A gilisztát eszeveszetten szereti, visszadobni szigorúan tilos.',
        kepek: [_ph('Fekete törpeharcsa 1'), _ph('Fekete törpeharcsa 2'), _ph('Fekete törpeharcsa 3')],
      ),
      Halfaj(
        id: 'hal_70', nev: 'Pataki szajbling', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Európai vizekbe is betelepített, észak-amerikai származású pisztrángféle (Díszes szaibling néven is ismert). Hátoldala sötétzöld, fémes fényű, melyet elszórtan narancssárgás, világosabb pettyek tarkítanak (nincs rajtuk világos udvar, mint a sebes pisztrángén). Az alacsony hőmérsékletű (max 15-18°C), oxigéndús patakokat kedveli. Kis méretű támolygó kanállal, apró twisterrel vagy nedvesléggyel pergetve lehet rácserkelni.',
        kepek: [_ph('Pataki szajbling 1'), _ph('Pataki szajbling 2'), _ph('Pataki szajbling 3')],
      ),
      Halfaj(
        id: 'hal_71', nev: 'Tüskés pikó', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Mindössze pár centis kis "páncélos" lovagja vizeinknek. Az oldalát apró csontlemezkék borítják pikkelyek helyett, a hátán pedig 3 (ritkábban 4) különálló, erős és hegyes tüske meredezik védekezésképp. A hím igazi építőmester: növényi szálakból hord össze kis fészket a fenéken az ikrák számára, és agresszíven védi azt. Habár elszaporodva képes kárt tenni az őshonos halak ikrájában, maga a faj ritka biológiai érdekesség és védett.',
        kepek: [_ph('Tüskés pikó 1'), _ph('Tüskés pikó 2'), _ph('Tüskés pikó 3')],
      ),
      Halfaj(
        id: 'hal_72', nev: 'Folyami géb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A Duna mentén a Fekete-tengerből invázió-szerűen felszaporodott apróhal. Szürkésbarna, foltos teste és jellegzetesen összeolvadt hasúszója (mely tapadókorongként funkcionál a köveken) van. Olyan szinten lepik el a kövezéseket, kőgátakat, hogy sokszor lehetetlenné teszik a finomszerelékes parti horgászatot: azonnal lerágják a csontit, gilisztát, pelleteket. Káros faj lévén el kell pusztítani.',
        kepek: [_ph('Folyami géb 1'), _ph('Folyami géb 2'), _ph('Folyami géb 3')],
      ),
      Halfaj(
        id: 'hal_73', nev: 'Kaukázusi törpegéb', kategoria: 'Ragadozó', statusz: 'Inváziós',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'A legkisebb méretű hazai inváziós gébfélénk, testhossza mindössze 3-4 cm, így a finomabb hálókon is átfér. Emiatt villámgyorsan bejut az összes csatornába és tórendszerbe. Halványabb, sárgás-áttetsző teste van apró pöttyökkel. Kis mérete ellenére is tizedeli a védett halak (pl. ökle) ikráját. Törvényi kötelezettség szerint vízbe visszakerülése tiltott.',
        kepek: [_ph('Kaukázusi törpegéb 1'), _ph('Kaukázusi törpegéb 2'), _ph('Kaukázusi törpegéb 3')],
      ),
      Halfaj(
        id: 'hal_74', nev: 'Gyöngyös koncér', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Nevét a hátpikkelyein fénylő "gyöngyszemekre" emlékeztető apró dudorokról, és a pikkelyek széleit keretező fekete, hálózatos mintáról kapta. Izmos, ezüstös színű pontyféle folyóvízi hal. Súlya az 1 kilót ritkán haladja meg, áramlatkedvelő alkatú, lárvákkal, rovarokkal táplálkozik a partmenti sodros részeken. Mivel nagyon kevés hazai folyóban él stabil állománya (pl. Rába), kiemelt védelmet kapott.',
        kepek: [_ph('Gyöngyös koncér 1'), _ph('Gyöngyös koncér 2'), _ph('Gyöngyös koncér 3')],
      ),
      Halfaj(
        id: 'hal_75', nev: 'Nyúldomolykó', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A fejes domolykó karcsúbb, nyúlánkabb "testvére". Feje sokkal kisebb, orra kissé megnyúlt, tompán lekerekített (innen a "nyúl" hasonlat), orrnyílásai feltűnően nagyok. A sebes, hegyi és dombvidéki, kristálytiszta folyóvizek elmaradhatatlan hala (lenne), de a vízszennyezések és duzzasztások miatt erősen veszélyeztetett és védett. Mindenevő, de rovarokra jobban fókuszál rokonánál.',
        kepek: [_ph('Nyúldomolykó 1'), _ph('Nyúldomolykó 2'), _ph('Nyúldomolykó 3')],
      ),
      Halfaj(
        id: 'hal_76', nev: 'Petényi-márna', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Bár a nagy márnához hasonló, méreteiben jóval alulmarad (maximum 20-25 cm). Nevét Petényi Salamon János, a hazai madár- és haltan híres kutatója tiszteletére kapta. Felső és alsó uszonyain, valamint az oldalán is sötét, barnás foltsorok (pöttyök) találhatók, melyek jól megkülönböztetik nagy testvérétől. Tisza vizű, sebes patakok, köves hegyi vizek ritka, szigorúan védett aljzatlakó kincse.',
        kepek: [_ph('Petényi-márna 1'), _ph('Petényi-márna 2'), _ph('Petényi-márna 3')],
      ),
      Halfaj(
        id: 'hal_77', nev: 'Kurta baing', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Megjelenése kísértetiesen emlékeztet egy kisméretű, 10-12 centiméteres balinra. Szája felső állású, mélyen bemetszett. Különlegessége a hasán futó éles pikkelyél. Igazi "mikro-ragadozó": a felszín közelében ólálkodik és hihetetlen fürgeséggel rabol rá a nála alig kisebb halfajok ivadékaira és vízre hulló rovarokra. Mocsaras, dús növényzetű vizeink egyre ritkább, oltalmat igénylő faja.',
        kepek: [_ph('Kurta baing 1'), _ph('Kurta baing 2'), _ph('Kurta baing 3')],
      ),
      Halfaj(
        id: 'hal_78', nev: 'Sujtásos küsz', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A hagyományos sneci "elegánsabb" rokona. Teste zömökebb, a feje tompább. A legfőbb különbségét a kopoltyúfedőtől a faroktőig húzódó, sötétkékes, lila vagy ólomszínű hosszanti sáv adja, amely úgy fest az ezüst testén, mint egy katonai sujtás. Kifejezetten a tiszta vizű, gyorsabb áramlású folyószakaszokon él csapatokban. Fogása esetén fokozott körültekintéssel kell eljárni és visszahelyezni.',
        kepek: [_ph('Sujtásos küsz 1'), _ph('Sujtásos küsz 2'), _ph('Sujtásos küsz 3')],
      ),
      Halfaj(
        id: 'hal_79', nev: 'Vaskos csabak', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Kis termetű, orsó formájú, sötétebb (sárgás-barnás, a hátán feketés) tónusú, vastag pikkelyes folyóvízi halunk. Orra testéhez képest tompa. Kifejezetten a közép-hegységek hideg, kavicsos, gyorsan zubogó patakjaiban él, onnan az alföldi, lassú szakaszokra nem úszik le. Mivel nagyon érzékeny az oxigén szintre és a folyók duzzasztására, kizárólag a legtisztább vizeinkben marad meg, emiatt védett.',
        kepek: [_ph('Vaskos csabak 1'), _ph('Vaskos csabak 2'), _ph('Vaskos csabak 3')],
      ),
      Halfaj(
        id: 'hal_80', nev: 'Dunai nagyhering', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Klasszikusan tengerben élő (anadrom), hering-szerű vándorhal. Formája nyúlánk, ezüstös testét könnyen leváló apró pikkelyek borítják, szájában hegyes fogak is ülnek. A Fekete-tengerből egészen a magyarországi Duna-szakaszokig képes volt felúszni hatalmas rajokban, hogy édesvízben ívjon. Ma a Vaskapu-erőmű betonfala miatt a felúszása lehetetlen, hajtása legendává vált; az elvétve felbukkanó (zsilipeken átjutó) példányai szigorúan védettek.',
        kepek: [_ph('Dunai nagyhering 1'), _ph('Dunai nagyhering 2'), _ph('Dunai nagyhering 3')],
      ),
      Halfaj(
        id: 'hal_81', nev: 'Széles durbincs', kategoria: 'Ragadozó', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'A vágó és a selymes durbincsnál sokkal magasabb hátú, zömökebb testalkatú ("szélesebb") sügérféle. Testén 4-5 nagyobb, határozott sötét keresztsáv húzódik végig, amely kissé zebracsíkossá teszi. Mély, gyorsabb folyású és iszapmentes folyóink (például a Duna mélyebb gödrei) aljzatán kutat táplálék után. Súlyos állománycsökkenése okán felvették a hazai természetvédelmi oltalom alatt álló halak listájára.',
        kepek: [_ph('Széles durbincs 1'), _ph('Széles durbincs 2'), _ph('Széles durbincs 3')],
      ),
      Halfaj(
        id: 'hal_82', nev: 'Halványfoltú küllő', kategoria: 'Békés', statusz: 'Védett',
        meretKorlatozas: '-', darabKorlatozas: '-', tilalmiIdoszak: 'Egész évben', szabalyozasEve: '2024',
        megjegyzes: 'Küllemében rendkívül hasonlít a fenékjáró küllőre: hengeres test, fenékre lapuló életmód és bajuszszálak az alsó szájnál. Fontos megkülönböztető jele, hogy az oldalán lévő sötét foltok kisebbek, határozatlanabbak ("halványabbak"), és sosem olvadnak egybe a hát felé mutató sötét sávval. Csak a tiszta vizű alföldi és dombvidéki homokos, áramló szakaszokon marad életben. Fogása esetén tilos megsérteni.',
        kepek: [_ph('Halványfoltú küllő 1'), _ph('Halványfoltú küllő 2'), _ph('Halványfoltú küllő 3')],
      ),
      Halfaj(
        id: 'hal_83', nev: 'Lénai tok', kategoria: 'Ragadozó', statusz: 'Fogható (Idegenhonos)',
        meretKorlatozas: 'Nincs', darabKorlatozas: 'Nincs', tilalmiIdoszak: 'Nincs', szabalyozasEve: '2024',
        megjegyzes: 'Ahogy a neve is mutatja, eredetileg a szibériai Léna folyó vízrendszeréből származó, hihetetlenül jól alkalmazkodó halfaj. A hazai tógazdaságok és intenzív telepítésű horgásztavak leggyakoribb "tokhala". Keresztmetszete csillag alakú (a csontos vértek miatt), orra megnyúlt, harcsaszerű bajuszszálakkal a porszívó-szája előtt. Pelletekkel, sajttal és büdös bojlikkal egész évben (még jég alól is!) nagy eséllyel fogható sportgép.',
        kepek: [_ph('Lénai tok 1'), _ph('Lénai tok 2'), _ph('Lénai tok 3')],
      ),
    ];
  }
}
